myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'
urlpatterns = [
    path('', views.main, name="main"),
    path('form_c', views.form_c, name='form_c'),
    path('form_m', views.form_m, name='form_m'),
    path('evaluate', views.evaluate, name="evaluate"),
    path('results', views.results, name="results")
]

statistika/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls'))
]

myapp/models.py
from django.db import models

# Create your models here.


class Data(models.Model):
    pohlavi = models.CharField(max_length=5)
    vek = models.IntegerField()
    vyska = models.IntegerField()
    delkaspanku = models.FloatField()
    casvstavani = models.TimeField()
    TypMobilu = models.CharField(max_length=20)
    CasNaSocialnich = models.FloatField(max_length=20)

    def __str__(self):
        return f"{self.pohlavi}-{self.vek}-{self.vyska}-{self.delkaspanku}-{self.casvstavani}-{self.TypMobilu}-{self.CasNaSocialnich}"


class Graphs(models.Model):

    class Meta:
        verbose_name_plural = 'graphs'

    pohlavi_kolac = models.CharField(max_length=100000, default='default')
    pohlavi_hist = models.CharField(max_length=100000, default='default')

    vysky_hist_muzi = models.CharField(max_length=100000, default='default')
    vysky_hist_zeny = models.CharField(max_length=100000, default='default')
    vysky_hist = models.CharField(max_length=100000, default='default')

    vysky_graph = models.CharField(max_length=100000)
    vysky_graph_muzi_a_zeny = models.CharField(max_length=100000, default='default')

    delky_spanku_hist = models.CharField(max_length=100000, default='default')
    delky_spanku_hist_muzi = models.CharField(max_length=100000, default='default')
    delky_spanku_hist_zeny = models.CharField(max_length=100000, default='default')

    delky_spanku_graph = models.CharField(max_length=100000, default='default')
    delky_spanku_graph_muzi_a_zeny = models.CharField(max_length=100000, default='default')

    cas_na_soc_hist = models.CharField(max_length=100000, default='default')
    cas_na_soc_hist_muzi = models.CharField(max_length=100000, default='default')
    cas_na_soc_hist_zeny = models.CharField(max_length=100000, default='default')

    cas_na_soc_graph = models.CharField(max_length=100000, default='default')
    cas_na_soc_graph_muzi_a_zeny = models.CharField(max_length=100000, default='default')

    typy_mobilu_kolac = models.CharField(max_length=100000, default='default')
    typy_mobilu_hist = models.CharField(max_length=100000, default='default')

    cas_vstavani_hist = models.CharField(max_length=100000, default='default')
    cas_vstavani_hist_muzi = models.CharField(max_length=100000, default='default')
    cas_vstavani_hist_zeny = models.CharField(max_length=100000, default='default')

    cas_vstavani_graph = models.CharField(max_length=100000, default='default')
    cas_vstavani_graph_muzi_a_zeny = models.CharField(max_length=100000, default='default')

myapp/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from .models import Data, Graphs
import pandas as pd
from functions import validate_form_input, create_graphs

def main(request):
    return render(request, 'myapp/get_size.html')

def form_c(request):
    return render(request, 'myapp/form_c.html')

def form_m(request):
    return render(request, 'myapp/form_m.html')

def evaluate(request):
    came_from = request.META['HTTP_REFERER'].split('/')[-1]

    if request.method == 'POST':
        form = request.POST
        result_of_validation = validate_form_input(form)
        if result_of_validation[0]:
            Data.objects.create(
                pohlavi=form['pohlavi'],
                vek=form['vek'],
                vyska=form['vyska'],
                delkaspanku=form['delka-spanku'].replace(',', '.'),
                casvstavani=form['cas-vstavani'],
                TypMobilu=form['typ-mobilu'],
                CasNaSocialnich=form['socialni-site'].replace(',', '.')
            )
            return HttpResponseRedirect(f"results?t={came_from[-1]}")
        else:
            context = {
                'error': True,
                'vyska': result_of_validation[1]['vyska'],
                'delka_spanku': result_of_validation[1]['delka_spanku'],
                'cas_vstavani': result_of_validation[1]['cas_vstavani'],
                'socialni_site': result_of_validation[1]['socialni_site'],
                'vek_prefilled': form['vek'],
                'vyska_prefilled': form['vyska'],
                'delka_spanku_prefilled': form['delka-spanku'],
                'cas_vstavani_prefilled': form['cas-vstavani'],
                'socialne_site_prefilled': form['socialni-site']
            }
            return render(request, f'myapp/{came_from}.html', context)
    else:
        return HttpResponseRedirect(reverse('myapp:main'))


def results(request):
    came_from = request.META['HTTP_REFERER'].split('/')[-1]
    print(came_from)
    if came_from[:4] == 'form':
        type = came_from[-1]
    else:
        type = request.GET['t']
    df_pohlavi = pd.DataFrame(Data.objects.all().values('pohlavi'))
    if len(df_pohlavi[df_pohlavi['pohlavi'] == 'muz']) < 14 or len(df_pohlavi[df_pohlavi['pohlavi'] == 'zena']) < 14:
        if type == 'm':
            return render(request, 'myapp/not_enought_m.html')
        else:
            return render(request, 'myapp/not_enought_c.html')

    else:
        if Graphs.objects.all():
            Graphs.objects.all().delete()
        create_graphs()
        graphs = Graphs.objects.all()
        graphs = graphs[len(graphs) - 1]
        context = {
            'pohlavi_kolac': graphs.pohlavi_kolac,
            'pohlavi_hist': graphs.pohlavi_hist,
            'vysky_hist': graphs.vysky_hist,
            'vysky_hist_muzi': graphs.vysky_hist_muzi,
            'vysky_hist_zeny': graphs.vysky_hist_zeny,
            'vysky_grafy': graphs.vysky_graph,
            'vysky_grafy_muzi_a_zeny': graphs.vysky_graph_muzi_a_zeny,
            'delky_spanku_hist': graphs.delky_spanku_hist,
            'delky_spanku_hist_muzi': graphs.delky_spanku_hist_muzi,
            'delky_spanku_hist_zeny': graphs.delky_spanku_hist_zeny,
            'delky_spanku_grafy': graphs.delky_spanku_graph,
            'delky_spanku_grafy_muzi_a_zeny': graphs.delky_spanku_graph_muzi_a_zeny,
            'typy_mobilu_kolac': graphs.typy_mobilu_kolac,
            'typy_mobilu_sloupcovy': graphs.typy_mobilu_hist,
            'cas_na_soc_hist_vsichni': graphs.cas_na_soc_hist,
            'cas_na_soc_hist_muzi': graphs.cas_na_soc_hist_muzi,
            'cas_na_soc_hist_zeny': graphs.cas_na_soc_hist_zeny,
            'cas_na_soc_grafy_vsichni': graphs.cas_na_soc_graph,
            'cas_na_soc_grafy_muzi_a_zeny': graphs.cas_na_soc_graph_muzi_a_zeny,
            'cas_vstavani_hist_vsichni': graphs.cas_vstavani_hist,
            'cas_vstavani_hist_muzi': graphs.cas_vstavani_hist_muzi,
            'cas_vstavani_hist_zeny': graphs.cas_vstavani_hist_zeny,
            'cas_vstavani_grafy_vsichni': graphs.cas_vstavani_graph,
            'cas_vstavani_grafy_muzi_a_zeny': graphs.cas_vstavani_graph_muzi_a_zeny
        }
        return render(request, 'myapp/results.html', context=context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script data-require="jquery@1.12.4" data-semver="1.12.4" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link type="text/css" rel="stylesheet" href="/static/css/style.css?{% now "U" %}">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <div class="row">
        <header class="blue darken-2">
            <nav class="blue darken-2">
                <div class="container nav-wrapper">
                    <a href="" class="brand-logo"><i class="large material-icons">insert_chart</i>Projekt Statistika</a>
                    <ul class="right hide-on-med-and-down">
                        <li><a href="https://gjn.cz" target="_blank">Gymnázium Jana Nerudy</a></li>
                    </ul>
                </div>
            </nav>
        </header>
    </div>

    <main>
        {% block content %}

        {% endblock content %}
    </main>
    <script type="text/javascript" src="/static/js/javascripts.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('select').formSelect();
        });
    </script>
    <script type="text/javascript">
          $(document).ready(function(){
            $('.tabs').tabs();
          });
    </script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>

</html>

templates/myapp/form_c.html
{% extends 'base.html' %}

{% block title %}Statistika -- Formulář{% endblock %}

{% block content %}
<div class="container">
    <br>
    <br>
    {% if error %}
        <div class="row">
            <div class="card-panel col s12 center red accent-4 white-text">Došlo k chybnému zadání. Některá výběrová pole se mohla resetovat!</div>
        </div>
    {% endif %}
    <br>
    <br>
    <div class="row">
        <form action="{% url 'myapp:evaluate' %}" class="col s12" method="post" autocomplete="off">
            {% csrf_token %}

            <div class="card-panel teal lighten-2 center white-text">Základní údaje</div>

            <div class="row">
                <div class="input-field col s12">
                    <select name="pohlavi">
                        <option value="muz">Muž</option>
                        <option value="zena">Žena</option>
                    </select>
                    <label>Pohlaví</label>
                </div>
            </div>

            <p class="range-field">Věk:
                <input type="range" min="5" max="100" value="{{ vek_prefilled }}" name="vek">
            </p>

            <div class="row">
                <div class="input-field col s12">
                    <input type="text" class="{{ vyska }}" name="vyska" id="vyska" value="{{ vyska_prefilled }}">
                    <label for="vyska">Výška (v cm)</label>
                    <span class="helper-text" data-error="Neplatná výška" data-success=""></span>
                </div>
            </div>

            <div class="card-panel teal lighten-2 center white-text">Spánek</div>

            <div class="row">
                <div class="input-field col s12">
                    <input id="delka-spanku" name="delka-spanku" type="text" class="{{ delka_spanku }}" value="{{ delka_spanku_prefilled }}">
                    <label for="delka-spanku">Délka spánku za normálního pracovního dne (v hodinách)</label>
                    <span class="helper-text" data-error="Neplatná délka spánku" data-success=""></span>
                </div>
            </div>

            <div class="row">
                <div class="input-field col s12">
                    <input id="cas-vstavani" value="{{ cas_vstavani_prefilled }}" name="cas-vstavani" class="timepicker {{ cas_vstavani }}" placeholder="Čas kdy vstávám z postele za normálního pracovního dne">
                    <span class="helper-text" data-error="Neplatný čas"></span>
                </div>
            </div>

            <div class="card-panel teal lighten-2 center white-text">Technologie</div>

            <div class="row">
                <div class="input-field col s12">
                    <select name="typ-mobilu" class="typ_mobilu">
                        <option value="Android">Android</option>
                        <option value="IOS">IOS</option>
                        <option value="tlačítkový">Tlačítkový</option>
                        <option value="jiny">Jiný</option>
                        <option value="nemá mobil">Nemam mobil</option>
                    </select>
                    <label>Typ mobilu</label>
                </div>
            </div>

            <div class="row">
                <div class="input-field col s12">
                    <input class="{{ socialni_site }}" id="socialni-site" name="socialni-site" type="text" value="{{ socialne_site_prefilled }}">
                    <label for="socialni-site">Čas denně strávení na sociálních sítích (v hodinách)</label>
                    <span class="helper-text" data-success="" data-error="Neplatný čas"></span>
                </div>
            </div>

            <button class="btn waves-effect waves-light" type="submit">Odeslat
                <i class="material-icons right">send</i>
            </button>
            <a class="btn waves-effect waves-light" href="{% url 'myapp:results' %}">Průběžná statistika</a>

        </form>

    </div>
</div>
{% endblock content %}

templates/myapp/form_m.html
<html>
    <head>
        <meta charset="UTF-8">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <script data-require="jquery@1.12.4" data-semver="1.12.4" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <link type="text/css" rel="stylesheet" href="/static/css/style.css?{% now "U" %}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Statistika -- Formulář</title>
    </head>

    <body>
        <form action="{% url 'myapp:evaluate' %}" method="post" autocomplete="off">
            {% csrf_token %}

            <div class="row">
                <div class="col s12 m4 offset-m4">
                    <div class="card z-depth-4">
                        <div class="card-content teal lighten-2 black-text">
                            <span class="card-title">Statistika</span>
                        </div>
                        <div class="card-content">

                            <div class="input-field">
                                <select name="pohlavi">
                                    <option value="muz">Muž</option>
                                    <option value="zena">Žena</option>
                                </select>
                                <label>Pohlaví</label>
                            </div>

                            <br>
                            <p class="range-field">Věk:
                                <input type="range" min="5" max="100" value="{{ vek_prefilled }}" name="vek">
                            </p>

                            <div class="input-field">
                                <input type="text" class="{{ vyska }}" name="vyska" id="vyska" value="{{ vyska_prefilled }}">
                                <label for="vyska">Výška (v cm)</label>
                                <span class="helper-text" data-error="Neplatná výška" data-success=""></span>
                            </div>

                            <div class="card-panel teal lighten-2 center white-text">Spánek</div>

                            <div class="input-field">
                                <input id="delka-spanku" name="delka-spanku" type="text" class="{{ delka_spanku }}" value="{{ delka_spanku_prefilled }}">
                                <label for="delka-spanku">Průměrna délka spánku (v hodinách)</label>
                                <span class="helper-text" data-error="Neplatná délka spánku" data-success=""></span>
                            </div>

                            <div class="input-field">
                                <input id="cas-vstavani" value="{{ cas_vstavani_prefilled }}" name="cas-vstavani" class="timepicker {{ cas_vstavani }}" placeholder="Čas kdy vstávám z postele v pracovní den">
                                <span class="helper-text" data-error="Neplatný čas"></span>
                            </div>

                            <div class="card-panel teal lighten-2 center white-text">Technologie</div>

                            <div class="input-field col s12">
                                <select name="typ-mobilu" class="typ_mobilu">
                                    <option value="Android">Android</option>
                                    <option value="IOS">IOS</option>
                                    <option value="tlačítkový">Tlačítkový</option>
                                    <option value="jiny">Jiný</option>
                                    <option value="nemá mobil">Nemam mobil</option>
                                </select>
                                <label>Typ mobilu</label>
                            </div>

                            <div class="input-field col s12">
                                <input class="{{ socialni_site }}" id="socialni-site" name="socialni-site" type="text" value="{{ socialne_site_prefilled }}">
                                <label for="socialni-site">Denní čas na soc. sítích (v hodinách)</label>
                                <span class="helper-text" data-success="" data-error="Neplatný čas"></span>
                            </div>

                            <button class="btn waves-effect waves-light" type="submit">Odeslat
                                <i class="material-icons right">send</i>
                            </button>

                            <br>
                            <br>
                            <a class="btn waves-effect waves-light" href="{% url 'myapp:results' %}">Průběžná statistika</a>

                        </div>
                    </div>
                </div>
            </div>
        </form>



        <script type="text/javascript" src="/static/js/javascripts.js"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                $('select').formSelect();
            });
        </script>
        <script type="text/javascript">
              $(document).ready(function(){
                $('.tabs').tabs();
              });
        </script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    </body>
</html>

templates/myapp/get_size.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Loading ...</title>
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
</head>
<body>
    <script type="text/javascript" src="/static/js/get_screen_size.js"></script>
</body>
</html>

templates/myapp/not_enought.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Statistika -- Grafy</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
        <div class="container">
            <br>
            <br>
            <br>
            <br>
            <div class="card-panel teal lighten-2 center white-text">
                Po dosažení určitého počtu odpovědí, zde budou vygenerovány grafy.
            </div>
            <a class="btn waves-effect waves-light" href="/"><i class="material-icons left">arrow_back</i>Zpět</a>
        </div>
    {% endblock content %}
</body>
</html>

templates/myapp/not_enought_c.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Statistika -- Grafy</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
        <div class="container">
            <br>
            <br>
            <br>
            <br>
            <div class="card-panel teal lighten-2 center white-text">
                Po dosažení určitého počtu odpovědí, zde budou vygenerovány grafy.
            </div>
            <a class="btn waves-effect waves-light" href="/"><i class="material-icons left">arrow_back</i>Zpět</a>
        </div>
    {% endblock content %}
</body>
</html>

templates/myapp/not_enought_m.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Statistika -- Grafy</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <div class="row">
        <div class="col s12 m4 offset-m4">
            <div class="card z-depth-4">
                <div class="card-content teal lighten-2">
                    <span class="card-title center">Po dosažení určitého počtu odpovědí zde budou vygenerovány grafy</span>
                </div>
                <div class="card-content">
                    <a class="btn waves-effect waves-light" href="/"><i class="material-icons left">arrow_back</i>Zpět</a>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
</head>
<body>
    <p>It works</p>
</body>
</html>